### ISSUE TITLE
GitHub Actions: TODO

### ISSUE THREAD

**Issue by larsgw** [larsgw/pentatomoidea-nymphs#1]
- [x] Install xml2lua
- [x] Rebase existing commits
- [x] Fix figure paths
- [x] Add css
